spring:
  application:
    name: fampilot-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/fampilot_db
    username: fampilot_app
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

